### ISSUE TITLE
Can't understand failure

### ISSUE THREAD

**Issue by nigelhorne** [jonasbn/perl-test-timer#14]
What went wrong to cause this message?

"Test ran 9 seconds and did not exceed specified threshold of 9 seconds"

See http://www.cpantesters.org/cpan/report/aa2b3bdb-6bf3-1014-8790-aa4ee6406fa7

**Comment by jonasbn** [comment]
Extracted from the referenced link:

```
#   Failed test 'should be fully throttled'
#   at t/request.t line 60.
# Test ran 9 seconds and did not exceed specified threshold of 9 seconds
```

**Comment by nigelhorne** [comment]
That's the one, yes.  I  can't understand the sentence.

**Comment by jonasbn** [comment]
hi @nigelhorne 

I checked the code and I use a basic ´>´ so the time of `9` is not regarded as exceeding the specified threshold of `9`

Both `time_atleast`and `time_atmost` exercises this behaviour. So basically 9 does not exceed 9 :-/

Did you expect something else let me know your advice is valued.

`time_between` however does have an issue since it uses both `>=` and `<=` meaning that the actual values specified are included. This is however inconsistent with the behaviour described above.

So I would love to clarify the behaviour and address the issue with `time_between`.

Please let me know what you think, as stated your opinion is valued.

jonasbn

**Comment by jonasbn** [comment]
What I wrote is not completely correct `time_atmost` would demonstrate the issue, since it relies on the same construct with a lower threshold of `0`

**Comment by nigelhorne** [comment]
I don't think you're understanding what I'm getting at here.  The problem is that I can't decipher the message.  I'm sure there's something wrong at my end, not yours, I just can't fathom it.

Possibly this is a dup of the ticket I just raised, and in fact we have a difference of opinion of what "at least" means.

**Comment by jonasbn** [comment]
Okay, I will respond to issue #15 and I will close this issue.
